Repository NoBrainCp/nobrain-backend, pull requests merged in 2023-02, with the labels that each got.

#51 fix: remove duplication method in UserRequest
  src/main/java/com/nobrain/bookmarking/domain/user/dto/UserRequest.java
Labels: fix

#52 [Feature/bookmark api] 북마크 수정 삭제 API 및 기능 구현
  .gitignore
  build.gradle
  src/main/java/com/nobrain/bookmarking/domain/auth/service/TokenService.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark/controller/BookmarkController.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark/dto/BookmarkRequest.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark/entity/Bookmark.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark/exception/BookmarkNotFoundException.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark/repository/BookmarkQueryRepository.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark/repository/BookmarkQueryRepositoryImpl.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark/service/BookmarkService.java
  src/main/java/com/nobrain/bookmarking/domain/tag/entity/Tag.java
  src/main/java/com/nobrain/bookmarking/domain/tag/service/TagService.java
  src/main/java/com/nobrain/bookmarking/global/config/JpaConfig.java
  src/test/java/com/nobrain/bookmarking/domain/bookmark/repository/BookmarkQueryRepositoryImplTest.java
Labels: feat, refactor

#54 Feature/mail certification
  build.gradle
  src/main/java/com/nobrain/bookmarking/domain/mail/MailController.java
  src/main/java/com/nobrain/bookmarking/domain/mail/MailService.java
  src/main/resources/application.yml
  src/main/resources/template/mail.html
  src/main/resources/templates/mail.html
Labels: feat, fix

#58 [Feature/category api] 카테고리 수정, 삭제 API 구현
  src/main/java/com/nobrain/bookmarking/domain/category/controller/CategoryController.java
  src/main/java/com/nobrain/bookmarking/domain/category/dto/CategoryRequest.java
  src/main/java/com/nobrain/bookmarking/domain/category/entity/Category.java
  src/main/java/com/nobrain/bookmarking/domain/category/repository/CategoryRepository.java
  src/main/java/com/nobrain/bookmarking/domain/category/service/CategoryService.java
Labels: feat, refactor

#61 Feature/bookmark tag
  settings.gradle
  src/main/java/com/nobrain/bookmarking/domain/bookmark/controller/BookmarkController.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark/dto/BookmarkRequest.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark/entity/Bookmark.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark/exception/BookmarkDuplicationException.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark/repository/BookmarkRepository.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark/service/BookmarkService.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark_tag/entity/BookmarkTag.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark_tag/repository/BookmarkTagRepository.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark_tag/service/BookmarkTagService.java
  src/main/java/com/nobrain/bookmarking/domain/category/entity/Category.java
  src/main/java/com/nobrain/bookmarking/domain/tag/entity/Tag.java
  src/main/java/com/nobrain/bookmarking/domain/tag/repository/TagRepository.java
  src/main/java/com/nobrain/bookmarking/domain/tag/service/TagService.java
  src/main/java/com/nobrain/bookmarking/domain/user/entity/User.java
Labels: feat, refactor

#62 [#60] style: change package structure
  src/main/java/com/nobrain/bookmarking/global/config/JasyptConfig.java
  src/main/java/com/nobrain/bookmarking/global/config/SwaggerConfig.java
Labels: cleanup

#64 [#63] chore: separate development server environment
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: setting

#66 queydsl 빌드 경로 수정
  .gitignore
  build.gradle
Labels: bug

#70 [#69] feat: password check exception handler
  src/main/java/com/nobrain/bookmarking/domain/user/exception/handler/UserExceptionHandler.java
  src/main/java/com/nobrain/bookmarking/domain/user/service/UserSignService.java
  src/main/java/com/nobrain/bookmarking/global/error/ErrorCode.java
Labels: feat

#71 Feature/user exception handler
  src/main/java/com/nobrain/bookmarking/domain/user/exception/UserPasswordCheckException.java
  src/main/java/com/nobrain/bookmarking/domain/user/exception/handler/UserExceptionHandler.java
  src/main/java/com/nobrain/bookmarking/domain/user/service/UserSignService.java
  src/main/java/com/nobrain/bookmarking/global/error/ErrorCode.java
Labels: feat, refactor

#72 [#69] refactor: username duplication exception
  src/main/java/com/nobrain/bookmarking/domain/user/exception/UsernameDuplicationException.java
  src/main/java/com/nobrain/bookmarking/global/error/ErrorCode.java
Labels: feat

#73 feat: 비밀번호 변경 구현
  src/main/generated/com/nobrain/bookmarking/domain/bookmark/entity/QBookmark.java
  src/main/generated/com/nobrain/bookmarking/domain/category/entity/QCategory.java
  src/main/generated/com/nobrain/bookmarking/domain/follow/entity/QFollow.java
  src/main/generated/com/nobrain/bookmarking/domain/tag/entity/QTag.java
  src/main/generated/com/nobrain/bookmarking/domain/user/entity/QUser.java
  src/main/generated/com/nobrain/bookmarking/global/entity/QBaseTimeEntity.java
  src/main/java/com/nobrain/bookmarking/domain/user/controller/UserController.java
  src/main/java/com/nobrain/bookmarking/domain/user/dto/UserRequest.java
  src/main/java/com/nobrain/bookmarking/domain/user/entity/User.java
  src/main/java/com/nobrain/bookmarking/domain/user/service/UserService.java
  src/main/resources/application.yml
Labels: feat

#77 Feature/send mail login
  .gitignore
  build.gradle
  src/main/java/com/nobrain/bookmarking/domain/certification/mail/MailController.java
  src/main/java/com/nobrain/bookmarking/domain/certification/mail/MailService.java
  src/main/java/com/nobrain/bookmarking/domain/certification/mail/dto/MailRequest.java
  src/main/java/com/nobrain/bookmarking/domain/certification/phone/PhoneController.java
  src/main/java/com/nobrain/bookmarking/domain/certification/phone/PhoneService.java
  src/main/resources/application-API-KEY.yml
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: feat, refactor

#79 Refactor/user api
  src/main/java/com/nobrain/bookmarking/domain/user/controller/UserController.java
  src/main/java/com/nobrain/bookmarking/domain/user/controller/UserSignController.java
  src/main/java/com/nobrain/bookmarking/domain/user/dto/UserRequest.java
  src/main/java/com/nobrain/bookmarking/domain/user/dto/UserResponse.java
  src/main/java/com/nobrain/bookmarking/domain/user/entity/User.java
  src/main/java/com/nobrain/bookmarking/domain/user/service/UserService.java
  src/main/java/com/nobrain/bookmarking/domain/user/service/UserSignService.java
Labels: refactor

#81 Feature/message
  src/main/java/com/nobrain/bookmarking/domain/certification/dto/CertificationRequest.java
  src/main/java/com/nobrain/bookmarking/domain/certification/mail/MailController.java
  src/main/java/com/nobrain/bookmarking/domain/certification/mail/dto/MailRequest.java
  src/main/java/com/nobrain/bookmarking/domain/certification/phone/PhoneController.java
  src/main/java/com/nobrain/bookmarking/domain/certification/phone/PhoneService.java
  src/main/java/com/nobrain/bookmarking/domain/certification/phone/dto/PhoneRequest.java
  src/main/java/com/nobrain/bookmarking/global/error/handler/GlobalExceptionHandler.java
  src/main/java/com/nobrain/bookmarking/global/security/JwtAuthenticationFilter.java
  src/main/resources/static/sample.jpg
Labels: feat

#82 [#76] refactor: codeMessage
  src/main/java/com/nobrain/bookmarking/domain/certification/phone/PhoneService.java
Labels: refactor

#84 [#83] refactor: change phone controller response
  src/main/java/com/nobrain/bookmarking/domain/certification/phone/PhoneController.java
  src/main/java/com/nobrain/bookmarking/domain/certification/phone/PhoneService.java
Labels: refactor

#87 [#86] refactor: implemented phone number regular expression
  src/main/java/com/nobrain/bookmarking/domain/user/dto/UserRequest.java
Labels: refactor

#88 [#60] style: clean up api
  src/main/java/com/nobrain/bookmarking/domain/certification/mail/MailController.java
  src/main/java/com/nobrain/bookmarking/domain/certification/phone/PhoneController.java
  src/main/java/com/nobrain/bookmarking/domain/user/controller/UserController.java
  src/main/java/com/nobrain/bookmarking/domain/user/controller/UserSignController.java
Labels: cleanup

#90 Feature/bookmark validation
  src/main/java/com/nobrain/bookmarking/domain/bookmark/controller/BookmarkController.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark/dto/BookmarkRequest.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark/service/BookmarkService.java
Labels: feat
