Repository NoBrainCp/nobrain-backend, pull requests merged in 2023-03, with the labels that each got.

#92 [Refactor/user response] Profile 조회 API 수정 및 유저 Info 조회 API 구현
  src/main/java/com/nobrain/bookmarking/domain/user/controller/UserController.java
  src/main/java/com/nobrain/bookmarking/domain/user/dto/UserResponse.java
  src/main/java/com/nobrain/bookmarking/domain/user/exception/UserNotFoundException.java
  src/main/java/com/nobrain/bookmarking/domain/user/repository/UserRepository.java
  src/main/java/com/nobrain/bookmarking/domain/user/repository/mapping/UserInfo.java
  src/main/java/com/nobrain/bookmarking/domain/user/service/UserService.java
  src/main/java/com/nobrain/bookmarking/domain/user/service/UserSignService.java
Labels: feat, refactor

#95 Meta Image Crawler: Implemented meta image crawler
  build.gradle
  src/main/java/com/nobrain/bookmarking/domain/bookmark/controller/BookmarkController.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark/dto/BookmarkRequest.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark/dto/BookmarkResponse.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark/entity/Bookmark.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark/service/BookmarkService.java
  src/main/java/com/nobrain/bookmarking/domain/util/MetaImageCrawler.java
  src/main/java/com/nobrain/bookmarking/domain/util/exception/UrlNotFoundException.java
  src/main/java/com/nobrain/bookmarking/global/error/ErrorCode.java
Labels: feat

#97 Refactor/response
  src/main/java/com/nobrain/bookmarking/domain/bookmark/dto/BookmarkResponse.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark/service/BookmarkService.java
  src/main/java/com/nobrain/bookmarking/domain/category/dto/CategoryResponse.java
  src/main/java/com/nobrain/bookmarking/domain/category/service/CategoryService.java
Labels: feat, refactor

#99 [Feature/tag api] Tag API 구현
  src/main/java/com/nobrain/bookmarking/domain/bookmark/entity/Bookmark.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark_tag/controller/BookmarkTagController.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark_tag/dto/BookmarkTagResponse.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark_tag/dto/projection/BookmarkTagProjection.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark_tag/entity/BookmarkTag.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark_tag/repository/BookmarkTagQueryRepository.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark_tag/repository/BookmarkTagQueryRepositoryImpl.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark_tag/service/BookmarkTagService.java
  src/main/java/com/nobrain/bookmarking/domain/category/entity/Category.java
  src/main/java/com/nobrain/bookmarking/domain/tag/controller/TagController.java
  src/main/java/com/nobrain/bookmarking/domain/tag/dto/TagResponse.java
  src/main/java/com/nobrain/bookmarking/domain/tag/entity/Tag.java
  src/main/java/com/nobrain/bookmarking/domain/tag/repository/TagQueryRepository.java
  src/main/java/com/nobrain/bookmarking/domain/tag/repository/TagQueryRepositoryImpl.java
  src/main/java/com/nobrain/bookmarking/domain/tag/service/TagService.java
  src/main/java/com/nobrain/bookmarking/domain/user/dto/projection/UserInfo.java
  src/main/java/com/nobrain/bookmarking/domain/user/repository/UserRepository.java
  src/main/java/com/nobrain/bookmarking/domain/user/service/UserService.java
Labels: feat, refactor

#101 [Feature/bookmark private starred] 북마크 즐겨찾기 및 공개 기능 구현
  src/main/java/com/nobrain/bookmarking/domain/bookmark/controller/BookmarkController.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark/dto/BookmarkRequest.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark/dto/BookmarkResponse.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark/entity/Bookmark.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark/service/BookmarkService.java
Labels: feat

#104 [Feature/bookmark search] 전체 카테고리 북마크 검색 기능 구현
  src/main/java/com/nobrain/bookmarking/domain/bookmark/controller/BookmarkController.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark/entity/Bookmark.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark/repository/BookmarkRepository.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark/search/SearchCondition.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark/service/BookmarkService.java
  src/main/java/com/nobrain/bookmarking/domain/user/dto/UserResponse.java
  src/main/java/com/nobrain/bookmarking/domain/user/service/UserSignService.java
  src/main/java/com/nobrain/bookmarking/global/security/SecurityConfig.java
Labels: feat, refactor

#105 [#93] feat: cors setting using addCorsMappings method
  src/main/java/com/nobrain/bookmarking/global/config/WebConfig.java
  src/main/java/com/nobrain/bookmarking/global/security/SecurityConfig.java
Labels: feat

#108 refactor: change findAllCategoryInfoWithCount query
  src/main/java/com/nobrain/bookmarking/domain/category/controller/CategoryController.java
  src/main/java/com/nobrain/bookmarking/domain/category/repository/CategoryQueryRepositoryImpl.java
Labels: refactor

#112 [Feature/query optimization] 쿼리 최적화
  src/main/java/com/nobrain/bookmarking/domain/bookmark/repository/BookmarkQueryRepository.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark/repository/BookmarkQueryRepositoryImpl.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark_tag/repository/BookmarkTagQueryRepositoryImpl.java
  src/main/java/com/nobrain/bookmarking/domain/category/controller/CategoryController.java
  src/main/java/com/nobrain/bookmarking/domain/category/dto/CategoryRequest.java
  src/main/java/com/nobrain/bookmarking/domain/category/repository/CategoryQueryRepository.java
  src/main/java/com/nobrain/bookmarking/domain/category/repository/CategoryQueryRepositoryImpl.java
  src/main/java/com/nobrain/bookmarking/domain/category/service/CategoryService.java
  src/main/java/com/nobrain/bookmarking/domain/tag/controller/TagController.java
  src/main/java/com/nobrain/bookmarking/domain/tag/repository/TagQueryRepository.java
  src/main/java/com/nobrain/bookmarking/domain/tag/repository/TagQueryRepositoryImpl.java
  src/main/java/com/nobrain/bookmarking/domain/tag/service/TagService.java
  src/main/java/com/nobrain/bookmarking/domain/user/controller/UserController.java
  src/main/java/com/nobrain/bookmarking/domain/user/dto/projection/UserInfo.java
  src/main/java/com/nobrain/bookmarking/domain/user/repository/UserRepository.java
  src/main/java/com/nobrain/bookmarking/domain/user/service/UserService.java
Labels: refactor

#114 [#98] feat: implemented tag inquiry with bookmark id.
  src/main/java/com/nobrain/bookmarking/domain/tag/controller/TagController.java
  src/main/java/com/nobrain/bookmarking/domain/tag/repository/TagQueryRepository.java
  src/main/java/com/nobrain/bookmarking/domain/tag/repository/TagQueryRepositoryImpl.java
  src/main/java/com/nobrain/bookmarking/domain/tag/service/TagService.java
Labels: feat

#116 Refactor/bookmark api
  src/main/java/com/nobrain/bookmarking/domain/bookmark/dto/BookmarkResponse.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark/entity/Bookmark.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark/repository/BookmarkQueryRepository.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark/repository/BookmarkQueryRepositoryImpl.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark/service/BookmarkService.java
  src/main/java/com/nobrain/bookmarking/domain/category/controller/CategoryController.java
  src/main/java/com/nobrain/bookmarking/domain/category/repository/CategoryQueryRepository.java
  src/main/java/com/nobrain/bookmarking/domain/category/repository/CategoryQueryRepositoryImpl.java
  src/main/java/com/nobrain/bookmarking/domain/category/service/CategoryService.java
  src/main/java/com/nobrain/bookmarking/domain/tag/controller/TagController.java
Labels: feat, refactor

#120 [#119] feat: implemented api to determine follow
  src/main/java/com/nobrain/bookmarking/domain/follow/controller/FollowController.java
  src/main/java/com/nobrain/bookmarking/domain/follow/repository/FollowRepository.java
  src/main/java/com/nobrain/bookmarking/domain/follow/service/FollowService.java
Labels: feat

#125 [#124] refactor: change follow user response dto
  src/main/java/com/nobrain/bookmarking/domain/follow/dto/FollowResponse.java
  src/main/java/com/nobrain/bookmarking/domain/user/entity/User.java
Labels: refactor

#127 feature/change user password
  src/main/java/com/nobrain/bookmarking/domain/follow/repository/FollowRepository.java
  src/main/java/com/nobrain/bookmarking/domain/follow/service/FollowService.java
  src/main/java/com/nobrain/bookmarking/domain/user/controller/UserController.java
  src/main/java/com/nobrain/bookmarking/domain/user/dto/UserRequest.java
  src/main/java/com/nobrain/bookmarking/domain/user/entity/User.java
  src/main/java/com/nobrain/bookmarking/domain/user/service/UserService.java
Labels: feat, refactor

#129 category api
  src/main/java/com/nobrain/bookmarking/domain/bookmark/service/BookmarkService.java
  src/main/java/com/nobrain/bookmarking/domain/category/dto/CategoryRequest.java
  src/main/java/com/nobrain/bookmarking/domain/category/entity/Category.java
Labels: feat, refactor

#131 [#130] refactor: change the follow find list to fetch join
  src/main/java/com/nobrain/bookmarking/domain/follow/repository/FollowRepository.java
Labels: refactor

#133 [Refactor/follow query] Follow Card List 조회 기능 개선
  src/main/java/com/nobrain/bookmarking/domain/follow/controller/FollowController.java
  src/main/java/com/nobrain/bookmarking/domain/follow/dto/FollowResponse.java
  src/main/java/com/nobrain/bookmarking/domain/follow/repository/FollowQueryRepository.java
  src/main/java/com/nobrain/bookmarking/domain/follow/repository/FollowQueryRepositoryImpl.java
  src/main/java/com/nobrain/bookmarking/domain/follow/service/FollowService.java
Labels: feat, refactor

#134 [#132] fix: fix isFollow column mapping value
  src/main/java/com/nobrain/bookmarking/domain/follow/repository/FollowQueryRepositoryImpl.java
Labels: fix

#136 [Feature/starred category] Starred Category 조회 기능 구현
  src/main/java/com/nobrain/bookmarking/domain/bookmark/controller/BookmarkController.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark/repository/BookmarkQueryRepository.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark/repository/BookmarkQueryRepositoryImpl.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark/service/BookmarkService.java
  src/main/java/com/nobrain/bookmarking/domain/category/controller/CategoryController.java
  src/main/java/com/nobrain/bookmarking/domain/category/service/CategoryService.java
Labels: feat, refactor

#137 [#135] feat: implemented starred bookmark count query
  src/main/java/com/nobrain/bookmarking/domain/bookmark/controller/BookmarkController.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark/repository/BookmarkQueryRepository.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark/repository/BookmarkQueryRepositoryImpl.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark/service/BookmarkService.java
Labels: feat

#141 feature/category query
  src/main/java/com/nobrain/bookmarking/domain/bookmark/controller/BookmarkController.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark/repository/BookmarkQueryRepository.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark/repository/BookmarkQueryRepositoryImpl.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark/service/BookmarkService.java
  src/main/java/com/nobrain/bookmarking/domain/category/controller/CategoryController.java
  src/main/java/com/nobrain/bookmarking/domain/category/repository/CategoryQueryRepository.java
  src/main/java/com/nobrain/bookmarking/domain/category/repository/CategoryQueryRepositoryImpl.java
  src/main/java/com/nobrain/bookmarking/domain/category/service/CategoryService.java
Labels: feat, refactor

#143 [#142] feat: implemented private bookmark search function and private…
  src/main/java/com/nobrain/bookmarking/domain/bookmark/controller/BookmarkController.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark/repository/BookmarkQueryRepository.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark/repository/BookmarkQueryRepositoryImpl.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark/service/BookmarkService.java
Labels: feat

#144 [Feature/profile image] AWS S3 bucket 연동
  .gitignore
  build.gradle
  src/main/java/com/nobrain/bookmarking/domain/user/controller/UserController.java
  src/main/java/com/nobrain/bookmarking/domain/user/service/UserService.java
  src/main/java/com/nobrain/bookmarking/global/error/ErrorCode.java
  src/main/java/com/nobrain/bookmarking/infra/certification/dto/CertificationRequest.java
  src/main/java/com/nobrain/bookmarking/infra/certification/mail/controller/MailController.java
  src/main/java/com/nobrain/bookmarking/infra/certification/mail/dto/MailRequest.java
  src/main/java/com/nobrain/bookmarking/infra/certification/mail/service/MailService.java
  src/main/java/com/nobrain/bookmarking/infra/certification/sms/controller/SmsController.java
  src/main/java/com/nobrain/bookmarking/infra/certification/sms/dto/SmsRequest.java
  src/main/java/com/nobrain/bookmarking/infra/certification/sms/service/SmsService.java
  src/main/java/com/nobrain/bookmarking/infra/s3/config/S3Config.java
  src/main/java/com/nobrain/bookmarking/infra/s3/exception/FileNotConvertException.java
  src/main/java/com/nobrain/bookmarking/infra/s3/service/S3Service.java
  src/main/resources/application.yml
Labels: feat, refactor

#147 Refactor/private condition query
  src/main/java/com/nobrain/bookmarking/domain/bookmark/controller/BookmarkController.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark/exception/BookmarkDuplicationException.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark/repository/BookmarkQueryRepository.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark/repository/BookmarkQueryRepositoryImpl.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark/repository/BookmarkRepository.java
  src/main/java/com/nobrain/bookmarking/domain/bookmark/service/BookmarkService.java
  src/main/java/com/nobrain/bookmarking/domain/category/repository/CategoryQueryRepository.java
  src/main/java/com/nobrain/bookmarking/domain/category/repository/CategoryQueryRepositoryImpl.java
  src/main/java/com/nobrain/bookmarking/domain/category/service/CategoryService.java
  src/main/java/com/nobrain/bookmarking/global/error/ErrorCode.java
Labels: refactor
